name: dlopen
description: Discover and load shared libraries at runtime
version: 0.1.0
homepage: https://github.com/filleduchaos/dart-bindgen/tree/stable/dlopen
author: PJ Essien <retrostereoyak@gmail.com>

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  path: any
  meta: any

dev_dependencies:
  ffi: ^0.1.3
  test: ^1.5.0
