name: bindgen
description: Generate Dart FFI bindings for C libraries
version: 0.1.0
homepage: https://github.com/filleduchaos/dart-bindgen
author: PJ Essien <retrostereoyak@gmail.com>

environment:
  sdk: ">=2.6.0 <3.0.0"

executables:
  bindgen:

dependencies:
  args: ^1.5.2
  ffi: ^0.1.3
  path: any
  meta: any
  recase: ^3.0.0

dev_dependencies:
  test: ^1.5.0
